"use client";

import { useEffect, useState } from "react";
import Link from "next/link";
import { useParams } from "next/navigation";
import { ConfidenceBreakdown } from "@/components/learning/ConfidenceBreakdown";
import { LifecycleActions } from "@/components/learning/LifecycleActions";
import { SupportingEvidenceList } from "@/components/learning/SupportingEvidenceList";
import {
  CATEGORY_LABEL,
  getSuggestion,
  STATUS_LABEL,
  statusBadgeClass,
  type SuggestionDetail,
} from "@/lib/learning";

export default function SuggestionDetailPage() {
  const params = useParams<{ id: string }>();
  const id = params?.id;
  const [suggestion, setSuggestion] = useState<SuggestionDetail | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");

  useEffect(() => {
    if (!id) return;
    let cancelled = false;
    setLoading(true);
    getSuggestion(id)
      .then((data) => {
        if (!cancelled) setSuggestion(data);
      })
      .catch((err) => {
        if (!cancelled)
          setError(err instanceof Error ? err.message : "Failed to load.");
      })
      .finally(() => {
        if (!cancelled) setLoading(false);
      });
    return () => {
      cancelled = true;
    };
  }, [id]);

  if (loading) return <p className="text-sm text-gray-500">Loading…</p>;
  if (error) return <p className="text-sm text-rose-600">{error}</p>;
  if (!suggestion)
    return <p className="text-sm text-gray-500">Suggestion not found.</p>;

  const outcomes = suggestion.outcome_distribution.counts;
  const consistencyPct = Math.round(
    suggestion.outcome_distribution.consistency * 100
  );

  return (
    <div className="space-y-6">
      <div>
        <Link
          href="/dashboard/learning"
          className="text-sm text-gray-500 hover:text-indigo-600"
        >
          ← Review Queue
        </Link>
        <div className="mt-1 flex items-center gap-2">
          <span
            className={`inline-block rounded-full px-2 py-0.5 text-xs font-medium ${statusBadgeClass(
              suggestion.status
            )}`}
          >
            {STATUS_LABEL[suggestion.status]}
          </span>
          <span className="rounded-full bg-gray-100 px-2 py-0.5 text-xs font-medium text-gray-700">
            {CATEGORY_LABEL[suggestion.category]}
          </span>
        </div>
        <h1 className="mt-2 text-2xl font-bold text-gray-900">
          {suggestion.title}
        </h1>
        <p className="mt-2 text-gray-700">{suggestion.description}</p>
      </div>

      <LifecycleActions
        suggestion={suggestion}
        onChanged={(updated) => setSuggestion(updated)}
      />

      <div className="grid gap-6 lg:grid-cols-3">
        <div className="lg:col-span-2 space-y-6">
          {/* 1. Why was this generated? */}
          <Section title="Why was this recommendation generated?">
            <p className="text-sm text-gray-700">
              {suggestion.reason_generated.summary ||
                "No summary produced by the synthesizer."}
            </p>
            <p className="mt-2 text-xs text-gray-500">
              Generated by {suggestion.reason_generated.synthesis_model || "unknown model"}{" "}
              (prompt {suggestion.reason_generated.synthesis_prompt_version || "n/a"}).
            </p>
          </Section>

          {/* 2. How many supporting conversations? */}
          <Section title="How many supporting conversations?">
            <div className="flex flex-wrap gap-6">
              <Stat
                label="Distinct evidence"
                value={suggestion.supporting_conversations.distinct_evidence_count}
              />
              <Stat
                label="Candidate recommendations"
                value={suggestion.supporting_conversations.candidate_count}
              />
            </div>
          </Section>

          {/* 3. What business outcome supports it? */}
          <Section title="What business outcome supports it?">
            <div className="flex flex-wrap gap-6">
              <Stat label="Positive" value={outcomes.positive ?? 0} tone="positive" />
              <Stat label="Negative" value={outcomes.negative ?? 0} tone="negative" />
              <Stat label="Neutral" value={outcomes.neutral ?? 0} />
              <Stat label="Consistency" value={`${consistencyPct}%`} />
            </div>
          </Section>

          {/* 4. What would change if implemented? */}
          <Section title="What would change if implemented?">
            {suggestion.proposed_changes.why_this_matters && (
              <p className="mb-3 text-sm text-gray-700">
                <span className="font-medium text-gray-900">Why it matters: </span>
                {suggestion.proposed_changes.why_this_matters}
              </p>
            )}
            {suggestion.proposed_changes.playbook_change && (
              <div className="mb-3">
                <div className="text-xs font-semibold uppercase tracking-wide text-gray-500">
                  Playbook change
                </div>
                <p className="mt-1 text-sm text-gray-700 whitespace-pre-line">
                  {suggestion.proposed_changes.playbook_change}
                </p>
              </div>
            )}
            {suggestion.proposed_changes.faq_addition && (
              <div className="mb-3">
                <div className="text-xs font-semibold uppercase tracking-wide text-gray-500">
                  FAQ addition
                </div>
                <p className="mt-1 text-sm text-gray-700 whitespace-pre-line">
                  {suggestion.proposed_changes.faq_addition}
                </p>
              </div>
            )}
            {suggestion.proposed_changes.publish_targets.length > 0 && (
              <div>
                <div className="text-xs font-semibold uppercase tracking-wide text-gray-500">
                  Would publish to
                </div>
                <p className="mt-1 text-sm text-gray-700">
                  {suggestion.proposed_changes.publish_targets.join(", ")}
                </p>
              </div>
            )}
          </Section>

          {/* Supporting Evidence — never "examples" */}
          <div>
            <h2 className="mb-3 text-lg font-semibold text-gray-900">
              Supporting Evidence
            </h2>
            <SupportingEvidenceList suggestionId={suggestion.id} />
          </div>
        </div>

        <div className="space-y-4">
          <ConfidenceBreakdown breakdown={suggestion.confidence_breakdown} />
          {suggestion.impact_json && Object.keys(suggestion.impact_json).length > 0 && (
            <div className="rounded-lg border border-gray-200 bg-white p-5">
              <h3 className="text-sm font-semibold text-gray-900">Measured Impact</h3>
              <pre className="mt-2 overflow-x-auto whitespace-pre-wrap text-xs text-gray-700">
                {JSON.stringify(suggestion.impact_json, null, 2)}
              </pre>
            </div>
          )}
          {suggestion.review_note && (
            <div className="rounded-lg border border-gray-200 bg-white p-5">
              <h3 className="text-sm font-semibold text-gray-900">Reviewer note</h3>
              <p className="mt-2 text-sm text-gray-700 whitespace-pre-line">
                {suggestion.review_note}
              </p>
            </div>
          )}
        </div>
      </div>
    </div>
  );
}

function Section({
  title,
  children,
}: {
  title: string;
  children: React.ReactNode;
}) {
  return (
    <section className="rounded-lg border border-gray-200 bg-white p-5">
      <h2 className="text-sm font-semibold uppercase tracking-wide text-gray-500">
        {title}
      </h2>
      <div className="mt-3">{children}</div>
    </section>
  );
}

function Stat({
  label,
  value,
  tone,
}: {
  label: string;
  value: number | string;
  tone?: "positive" | "negative";
}) {
  const color =
    tone === "positive"
      ? "text-emerald-700"
      : tone === "negative"
      ? "text-rose-700"
      : "text-gray-900";
  return (
    <div>
      <div className={`text-xl font-bold ${color}`}>{value}</div>
      <div className="text-xs text-gray-500">{label}</div>
    </div>
  );
}
