# Generated by Django 5.1.15 on 2026-08-19 00:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrgStatistics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_events', models.PositiveBigIntegerField(default=0)),
                ('last_event_at', models.DateTimeField(blank=True, null=True)),
                ('event_type_counts', models.JSONField(blank=True, default=dict)),
                ('runtime_counts', models.JSONField(blank=True, default=dict)),
                ('channel_counts', models.JSONField(blank=True, default=dict)),
                ('org', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='context_statistics', to='accounts.organization')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ContextRequestLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant_id', models.CharField(blank=True, help_text='Raw tenantId from the request. Kept even when it resolves to an org so we can spot mapping drift.', max_length=128)),
                ('runtime', models.CharField(help_text='"leadbridge" | "callio" | future runtimes.', max_length=32)),
                ('channel', models.CharField(blank=True, max_length=32)),
                ('event_type', models.CharField(blank=True, max_length=64)),
                ('customer_id', models.CharField(blank=True, max_length=128)),
                ('lead_id', models.CharField(blank=True, max_length=128)),
                ('conversation_id', models.CharField(blank=True, max_length=128)),
                ('request_payload', models.JSONField(blank=True, default=dict, help_text='Full request body. Keeps us honest about what runtimes actually send vs. what we assume.')),
                ('status', models.CharField(choices=[('no_context', 'No context'), ('context', 'Context returned')], default='no_context', max_length=16)),
                ('confidence', models.DecimalField(decimal_places=3, default=0, max_digits=4)),
                ('context_size_bytes', models.PositiveIntegerField(default=0, help_text='Byte length of the JSON-encoded response.context object. Zero when status = no_context.')),
                ('latency_ms', models.PositiveIntegerField(default=0, help_text='End-to-end generation time in ms — everything from view entry to response body ready.')),
                ('source_results', models.JSONField(blank=True, default=list, help_text='Per-source breakdown: [{name, priority, contributed, confidence, latency_ms, error}, ...]. Powers debugging without a DB row per source.')),
                ('returned_to_runtime', models.BooleanField(default=False, help_text='False in shadow mode (BEHAVIOR_CONTEXT_ENABLED off) — we ran the sources and logged the outcome but responded {"status":"no_context"} to the caller.')),
                ('context_version', models.CharField(blank=True, help_text='Engine version at generation time (e.g. "2.0"). Bumped by apps.context.engine when the merger algorithm changes.', max_length=16)),
                ('source_count', models.PositiveIntegerField(default=0, help_text='Count of Sources that contributed at least one fact / recommendation / warning to this response.')),
                ('org', models.ForeignKey(blank=True, help_text='Resolved from request.tenantId. Null when tenantId did not map to a known org — we still log the request so we can diagnose misrouted traffic.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='context_requests', to='accounts.organization')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['org', '-created_at'], name='context_con_org_id_e0ddf7_idx'), models.Index(fields=['runtime', '-created_at'], name='context_con_runtime_3ca6f2_idx'), models.Index(fields=['status', '-created_at'], name='context_con_status_73abb9_idx')],
            },
        ),
        migrations.CreateModel(
            name='CustomerHistoryAggregate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer_id', models.CharField(max_length=128)),
                ('total_events', models.PositiveIntegerField(default=0)),
                ('first_seen_at', models.DateTimeField(blank=True, null=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('event_type_counts', models.JSONField(blank=True, default=dict, help_text='{"new_lead": 3, "inbound_call": 7, ...}')),
                ('runtime_counts', models.JSONField(blank=True, default=dict, help_text='{"leadbridge": 5, "callio": 2}')),
                ('channel_counts', models.JSONField(blank=True, default=dict, help_text='{"sms": 4, "voice": 3}')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_history_aggregates', to='accounts.organization')),
            ],
            options={
                'indexes': [models.Index(fields=['org', '-last_seen_at'], name='context_cus_org_id_29efea_idx')],
                'constraints': [models.UniqueConstraint(fields=('org', 'customer_id'), name='context_customer_history_unique')],
            },
        ),
        migrations.CreateModel(
            name='EvidenceEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_kind', models.CharField(choices=[('runtime', 'Live runtime call'), ('historical', 'Historical backfill')], default='runtime', max_length=16)),
                ('runtime', models.CharField(help_text='"leadbridge" | "callio" | "serviceflow" | future systems. For historical imports, use the source system name.', max_length=32)),
                ('channel', models.CharField(blank=True, max_length=32)),
                ('event_type', models.CharField(blank=True, max_length=64)),
                ('customer_id', models.CharField(blank=True, max_length=128)),
                ('lead_id', models.CharField(blank=True, max_length=128)),
                ('conversation_id', models.CharField(blank=True, max_length=128)),
                ('external_id', models.CharField(blank=True, help_text='Source-system-native ID for historical imports. Empty for live runtime events (each request is inherently distinct).', max_length=255)),
                ('occurred_at', models.DateTimeField(help_text='When the real-world interaction happened. For runtime events this is server-receive time; for historical imports the caller supplies it.')),
                ('message_excerpt', models.CharField(blank=True, help_text='First 500 chars of the customer message for admin browsing. Full body lives in `payload`.', max_length=500)),
                ('payload', models.JSONField(blank=True, default=dict, help_text='Full request body (runtime) or record body (historical). Anything the sender wanted us to know.')),
                ('promoted_at', models.DateTimeField(blank=True, help_text='Timestamp at which this event was SUCCESSFULLY promoted into an `apps.learning.EvidenceInsight` row. Only set when promotion_status=PROMOTED. Null otherwise (pending, skipped, or failed).', null=True)),
                ('promotion_status', models.CharField(choices=[('pending', 'Pending eligibility check'), ('promoted', 'Promoted into EvidenceInsight'), ('skipped', 'Skipped per eligibility rules'), ('failed', 'Ingestion failure — retryable')], default='pending', help_text='Terminal state of the promotion pipeline for this event. Every event reaches a non-PENDING state after the eligibility evaluator runs — no event stays perpetually unprocessed.', max_length=16)),
                ('promotion_reason', models.CharField(blank=True, default='', help_text='Detail on the promotion decision. For SKIPPED: one of "skip_diagnostic" | "skip_incomplete" | "skip_synthetic" | "skip_duplicate" | "skip_unsupported". For FAILED: "failed:<ExceptionName>". Empty for PENDING / PROMOTED.', max_length=64)),
                ('promotion_checked_at', models.DateTimeField(blank=True, help_text='When the eligibility evaluator last ran against this event. Separate from promoted_at (only success time) so operators can tell "we looked at this and rejected it" from "we never looked at it yet".', null=True)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_events', to='accounts.organization')),
            ],
            options={
                'ordering': ['-occurred_at'],
                'indexes': [models.Index(fields=['org', 'customer_id', '-occurred_at'], name='context_evi_org_id_417b0f_idx'), models.Index(fields=['org', 'runtime', '-occurred_at'], name='context_evi_org_id_843d0c_idx'), models.Index(fields=['org', 'source_kind', '-occurred_at'], name='context_evi_org_id_827215_idx'), models.Index(fields=['org', 'promoted_at', 'occurred_at'], name='ctx_event_promo_queue_idx'), models.Index(fields=['org', 'promotion_status', 'promotion_reason'], name='ctx_event_promo_status_idx'), models.Index(fields=['conversation_id'], name='context_evi_convers_ff7e42_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('external_id__gt', '')), fields=('org', 'source_kind', 'external_id'), name='context_evidence_event_external_unique')],
            },
        ),
    ]
