# Generated by Django 5.1.15 on 2026-08-19 00:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('partial', 'Partial (budget exceeded, will resume)'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('triggered_by', models.CharField(choices=[('schedule', 'Schedule'), ('manual', 'Manual')], default='schedule', max_length=20)),
                ('window_start', models.DateTimeField(blank=True, null=True)),
                ('window_end', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('evidence_processed', models.PositiveIntegerField(default=0)),
                ('evidence_skipped', models.PositiveIntegerField(default=0)),
                ('suggestions_created', models.PositiveIntegerField(default=0)),
                ('cost_usd', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('error', models.TextField(blank=True)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_jobs', to='accounts.organization')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EvidenceInsight',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_system', models.CharField(help_text='Free-form source key, e.g. "leadbridge", "callio", "serviceflow".', max_length=64)),
                ('external_id', models.CharField(help_text='Evidence ID at the source system. Composite unique with source_system.', max_length=255)),
                ('evidence_type', models.CharField(choices=[('conversation', 'Conversation'), ('call', 'Call'), ('outcome', 'Outcome'), ('other', 'Other')], default='conversation', max_length=32)),
                ('occurred_at', models.DateTimeField(blank=True, help_text='When the real-world event happened at the source.', null=True)),
                ('outcome', models.CharField(blank=True, help_text='Business outcome from the source (booked, cancelled, won, lost, etc.). Never inferred.', max_length=64)),
                ('outcome_metadata', models.JSONField(blank=True, default=dict)),
                ('source_business_rules_version', models.CharField(blank=True, help_text='Playbook/business-rules version at the source at the time of the event. Lets us compare recommendations before/after rule changes.', max_length=64)),
                ('source_payload', models.JSONField(blank=True, default=dict, help_text='Raw evidence payload from the adapter (transcript, call data, outcome record, etc.).')),
                ('ingest_metadata', models.JSONField(blank=True, default=dict, help_text='Adapter-level metadata about the fetch itself (cursor, source URL, fetch time, etc.).')),
                ('ai_summary', models.TextField(blank=True, help_text='Short human-readable summary extracted from analysis_json.summary. For display only — not analyzed downstream.')),
                ('analysis_json', models.JSONField(blank=True, default=dict, help_text='Structured business learning from the analyzer: category, subcategory, customer_intent, outcome_analysis, candidate_playbook_rules, candidate_faq, signals, confidence. Schema versioned via analysis_prompt_version.')),
                ('raw_response', models.TextField(blank=True, help_text='Raw model output before JSON parsing. Kept so we can inspect exactly what the model returned when a recommendation looks wrong.')),
                ('analysis_model', models.CharField(blank=True, help_text='Model used, e.g. "claude-haiku-4-5-20251001".', max_length=64)),
                ('analysis_prompt_version', models.CharField(blank=True, help_text='Analyzer prompt version at analysis time, e.g. "conversation:v1". Bump when prompt changes so we can re-queue insights.', max_length=32)),
                ('analysis_cost_usd', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('analyzed_at', models.DateTimeField(blank=True, help_text='Null = still queued for analysis (resume queue).', null=True)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_insights', to='accounts.organization')),
                ('job', models.ForeignKey(blank=True, help_text='Job that created this insight; may differ from the job that analyzed it.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='insights', to='learning.learningjob')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LearningSuggestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('pricing', 'Pricing'), ('faq', 'FAQ'), ('qualification', 'Qualification flow'), ('playbook', 'Playbook rule'), ('missing_info', 'Missing information'), ('tone', 'Tone'), ('other', 'Other')], max_length=32)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('fingerprint', models.CharField(db_index=True, help_text='Normalized token union from supporting candidates; used for merging new candidates and rejection checks (Jaccard-based comparison).', max_length=512)),
                ('confidence', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('confidence_breakdown', models.JSONField(blank=True, default=dict, help_text='{llm, support, outcome_consistency, final} — components explaining the score.')),
                ('representative_examples', models.JSONField(blank=True, default=dict, help_text='{top: [3 examples], highest_confidence: {...}, newest: {...}} — each example = {candidate_id, evidence_id, snippet, source_system}.')),
                ('supporting_count', models.PositiveIntegerField(default=0, help_text='Denormalized count of supporting CandidateRecommendation rows.')),
                ('synthesis_json', models.JSONField(blank=True, default=dict, help_text='Full synthesis output: why_this_matters, supporting_evidence_summary, suggested_playbook_change, suggested_faq_addition.')),
                ('synthesis_model', models.CharField(blank=True, max_length=64)),
                ('synthesis_prompt_version', models.CharField(blank=True, max_length=32)),
                ('synthesis_cost_usd', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('new', 'New (freshly synthesized)'), ('under_review', 'Under review'), ('approved', 'Approved'), ('implemented', 'Implemented (published to target channel)'), ('measured', 'Measured (impact quantified)'), ('archived', 'Archived'), ('rejected', 'Rejected'), ('watchlist', 'Watchlist (below surface threshold)')], default='new', max_length=20)),
                ('publish_targets', models.JSONField(blank=True, default=list, help_text='Channel keys this suggestion should be published to when implemented (e.g. ["leadbridge_playbook", "callio_voice_rules"]). Empty in Phase 1; the approve endpoint persists this so a future publisher can pick it up without breaking the API contract.')),
                ('impact_json', models.JSONField(blank=True, default=dict, help_text='Before/after metrics captured when the suggestion transitions to MEASURED (e.g. {"win_rate_before": 0.42, "win_rate_after": 0.51, "sample_size": 320}).')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_note', models.TextField(blank=True)),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suggestions', to='learning.learningjob')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_suggestions', to='accounts.organization')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_suggestions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CandidateRecommendation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('playbook_rule', 'Playbook rule'), ('faq', 'FAQ')], max_length=20)),
                ('category', models.CharField(choices=[('pricing', 'Pricing'), ('faq', 'FAQ'), ('qualification', 'Qualification flow'), ('playbook', 'Playbook rule'), ('missing_info', 'Missing information'), ('tone', 'Tone'), ('other', 'Other')], help_text='Denormalized from analysis_json.category for filtering.', max_length=32)),
                ('title', models.CharField(help_text='For playbook_rule: rule title. For faq: the question.', max_length=400)),
                ('description', models.TextField(help_text='For playbook_rule: rule body. For faq: the answer.')),
                ('llm_confidence', models.DecimalField(decimal_places=2, default=0, help_text='Per-candidate confidence from the analyzer LLM.', max_digits=3)),
                ('outcome_signal', models.CharField(choices=[('positive', 'Positive (booked / won / recurring)'), ('negative', 'Negative (cancelled / lost / no_show)'), ('neutral', 'Neutral / unknown')], db_index=True, default='neutral', max_length=20)),
                ('fingerprint', models.CharField(db_index=True, help_text='Normalized token string; used for Jaccard clustering.', max_length=512)),
                ('tokens', models.JSONField(blank=True, default=list, help_text='Deduplicated token list matching fingerprint. Denormalized for fast set ops.')),
                ('clustered_at', models.DateTimeField(blank=True, help_text='Null = unclustered (resume queue for clustering).', null=True)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_recommendations', to='accounts.organization')),
                ('evidence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_recommendations', to='learning.evidenceinsight')),
                ('job', models.ForeignKey(blank=True, help_text='Job that produced this candidate.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidate_recommendations', to='learning.learningjob')),
                ('suggestion', models.ForeignKey(blank=True, help_text='Cluster this candidate was merged into. Null = unclustered (resume queue).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidate_recommendations', to='learning.learningsuggestion')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RejectedSuggestionSignature',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('pricing', 'Pricing'), ('faq', 'FAQ'), ('qualification', 'Qualification flow'), ('playbook', 'Playbook rule'), ('missing_info', 'Missing information'), ('tone', 'Tone'), ('other', 'Other')], max_length=32)),
                ('signature', models.CharField(help_text='Fingerprint of the rejected suggestion (token union of its candidates).', max_length=512)),
                ('tokens', models.JSONField(blank=True, default=list, help_text='Deduplicated tokens matching signature. Used for Jaccard comparison.')),
                ('rejection_reason', models.TextField(help_text='Required at rejection time. Persisted for future analyzer prompting ("customers rejected X for reason Y — do not re-recommend").')),
                ('expires_at', models.DateTimeField(help_text='90 days from rejection by default.')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rejected_suggestion_signatures', to='accounts.organization')),
                ('rejected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_suggestion_signatures', to=settings.AUTH_USER_MODEL)),
                ('rejected_suggestion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejection_signatures', to='learning.learningsuggestion')),
            ],
        ),
        migrations.CreateModel(
            name='SourceIntegration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_system', models.CharField(help_text='Adapter key: leadbridge / callio / serviceflow / ...', max_length=64)),
                ('url', models.CharField(blank=True, help_text='HTTPS endpoint the adapter GETs from.', max_length=500)),
                ('token', models.CharField(blank=True, help_text='Bearer token sent in Authorization header. Plain text in Phase 1; move to a secret manager once we ship real integrations.', max_length=512)),
                ('is_active', models.BooleanField(default=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('last_sync_status', models.CharField(choices=[('never', 'Never synced'), ('ok', 'OK'), ('error', 'Error')], default='never', max_length=20)),
                ('last_sync_error', models.TextField(blank=True)),
                ('last_sync_created', models.PositiveIntegerField(default=0)),
                ('last_sync_updated', models.PositiveIntegerField(default=0)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_integrations', to='accounts.organization')),
            ],
        ),
        migrations.AddIndex(
            model_name='learningjob',
            index=models.Index(fields=['status', '-started_at'], name='learning_le_status_867e9d_idx'),
        ),
        migrations.AddIndex(
            model_name='learningjob',
            index=models.Index(fields=['org', '-started_at'], name='learning_le_org_id_ba2f91_idx'),
        ),
        migrations.AddIndex(
            model_name='evidenceinsight',
            index=models.Index(fields=['analyzed_at'], name='learning_ev_analyze_fe5886_idx'),
        ),
        migrations.AddIndex(
            model_name='evidenceinsight',
            index=models.Index(fields=['source_system', '-occurred_at'], name='learning_ev_source__20b67c_idx'),
        ),
        migrations.AddIndex(
            model_name='evidenceinsight',
            index=models.Index(fields=['org', '-occurred_at'], name='learning_ev_org_id_626250_idx'),
        ),
        migrations.AddConstraint(
            model_name='evidenceinsight',
            constraint=models.UniqueConstraint(fields=('source_system', 'external_id'), name='learning_evidence_source_unique'),
        ),
        migrations.AddIndex(
            model_name='learningsuggestion',
            index=models.Index(fields=['status', '-created_at'], name='learning_le_status_8de765_idx'),
        ),
        migrations.AddIndex(
            model_name='learningsuggestion',
            index=models.Index(fields=['category', 'status'], name='learning_le_categor_a44f76_idx'),
        ),
        migrations.AddIndex(
            model_name='learningsuggestion',
            index=models.Index(fields=['org', 'status'], name='learning_le_org_id_1cd5a3_idx'),
        ),
        migrations.AddIndex(
            model_name='candidaterecommendation',
            index=models.Index(fields=['clustered_at'], name='learning_ca_cluster_a9097b_idx'),
        ),
        migrations.AddIndex(
            model_name='candidaterecommendation',
            index=models.Index(fields=['org', 'category', 'clustered_at'], name='learning_ca_org_id_cc7038_idx'),
        ),
        migrations.AddIndex(
            model_name='candidaterecommendation',
            index=models.Index(fields=['suggestion'], name='learning_ca_suggest_df78d9_idx'),
        ),
        migrations.AddIndex(
            model_name='rejectedsuggestionsignature',
            index=models.Index(fields=['org', 'category'], name='learning_re_org_id_e2a063_idx'),
        ),
        migrations.AddIndex(
            model_name='rejectedsuggestionsignature',
            index=models.Index(fields=['expires_at'], name='learning_re_expires_0905b9_idx'),
        ),
        migrations.AddConstraint(
            model_name='rejectedsuggestionsignature',
            constraint=models.UniqueConstraint(fields=('org', 'category', 'signature'), name='learning_rejected_signature_unique'),
        ),
        migrations.AddConstraint(
            model_name='sourceintegration',
            constraint=models.UniqueConstraint(fields=('org', 'source_system'), name='learning_source_integration_unique'),
        ),
    ]
