# Generated by Django 5.1.15 on 2026-08-19 00:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.CharField(max_length=64)),
                ('source_conversation_id', models.CharField(max_length=255)),
                ('channel', models.CharField(choices=[('voice', 'Voice'), ('sms', 'SMS'), ('chat', 'Chat'), ('unknown', 'Unknown')], default='unknown', max_length=16)),
                ('customer_phone', models.CharField(blank=True, default='', max_length=32)),
                ('customer_email', models.EmailField(blank=True, default='', max_length=254)),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('ingestion_status', models.CharField(choices=[('pending', 'Pending'), ('normalized', 'Normalized'), ('linked', 'Linked'), ('outcomes_resolved', 'Outcomes resolved'), ('emitted', 'Emitted to EvidencePipeline'), ('failed', 'Failed')], default='pending', max_length=32)),
                ('import_run_id', models.CharField(blank=True, default='', max_length=64)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='accounts.organization')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ConversationTurn',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_turn_id', models.CharField(max_length=255)),
                ('speaker', models.CharField(choices=[('customer', 'Customer'), ('agent', 'Agent'), ('system', 'System'), ('unknown', 'Unknown')], default='unknown', max_length=16)),
                ('direction', models.CharField(choices=[('inbound', 'Inbound'), ('outbound', 'Outbound'), ('unknown', 'Unknown')], default='unknown', max_length=16)),
                ('text', models.TextField(blank=True, default='')),
                ('occurred_at', models.DateTimeField()),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turns', to='conversations.conversation')),
            ],
            options={
                'ordering': ['occurred_at'],
            },
        ),
        migrations.CreateModel(
            name='EntityLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('target_system', models.CharField(choices=[('leadbridge', 'LeadBridge'), ('serviceflow', 'ServiceFlow')], max_length=32)),
                ('target_type', models.CharField(choices=[('lead', 'Lead'), ('customer', 'Customer'), ('opportunity', 'Opportunity'), ('job', 'Job'), ('appointment', 'Appointment')], max_length=32)),
                ('target_id', models.CharField(max_length=255)),
                ('match_method', models.CharField(choices=[('external_id', 'External ID'), ('phone_exact', 'Phone (exact match)'), ('email_exact', 'Email (exact match)'), ('manual', 'Manual')], max_length=32)),
                ('confidence', models.FloatField(default=1.0)),
                ('matched_at', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entity_links', to='conversations.conversation')),
            ],
            options={
                'ordering': ['-matched_at'],
            },
        ),
        migrations.CreateModel(
            name='OutcomeSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('captured_at', models.DateTimeField()),
                ('lb_status', models.CharField(blank=True, default='', max_length=64)),
                ('lb_engaged', models.BooleanField(blank=True, null=True)),
                ('lb_booked', models.BooleanField(blank=True, null=True)),
                ('lb_lost', models.BooleanField(blank=True, null=True)),
                ('lb_cancelled', models.BooleanField(blank=True, null=True)),
                ('sf_opportunity_status', models.CharField(blank=True, default='', max_length=64)),
                ('sf_booked', models.BooleanField(blank=True, null=True)),
                ('sf_completed', models.BooleanField(blank=True, null=True)),
                ('sf_cancelled', models.BooleanField(blank=True, null=True)),
                ('sf_revenue_cents', models.BigIntegerField(blank=True, null=True)),
                ('sf_recurring', models.BooleanField(blank=True, null=True)),
                ('sf_job_count', models.PositiveIntegerField(blank=True, null=True)),
                ('source_payload', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outcome_snapshots', to='conversations.conversation')),
            ],
            options={
                'ordering': ['-captured_at'],
            },
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['org', '-started_at'], name='conversatio_org_id_45e5a6_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['org', 'customer_phone'], name='conversatio_org_id_2f9295_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['org', 'source', '-started_at'], name='conversatio_org_id_68dd8f_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['ingestion_status'], name='conversatio_ingesti_81d38f_idx'),
        ),
        migrations.AddConstraint(
            model_name='conversation',
            constraint=models.UniqueConstraint(fields=('org', 'source', 'source_conversation_id'), name='conversations_org_source_extid_unique'),
        ),
        migrations.AddIndex(
            model_name='conversationturn',
            index=models.Index(fields=['conversation', 'occurred_at'], name='conversatio_convers_651973_idx'),
        ),
        migrations.AddConstraint(
            model_name='conversationturn',
            constraint=models.UniqueConstraint(fields=('conversation', 'source_turn_id'), name='conversation_turns_conv_srcid_unique'),
        ),
        migrations.AddIndex(
            model_name='entitylink',
            index=models.Index(fields=['target_system', 'target_type', 'target_id'], name='conversatio_target__9278a4_idx'),
        ),
        migrations.AddIndex(
            model_name='entitylink',
            index=models.Index(fields=['conversation', 'target_system'], name='conversatio_convers_a61514_idx'),
        ),
        migrations.AddConstraint(
            model_name='entitylink',
            constraint=models.UniqueConstraint(fields=('conversation', 'target_system', 'target_type', 'target_id', 'match_method'), name='entity_links_dedupe_unique'),
        ),
        migrations.AddIndex(
            model_name='outcomesnapshot',
            index=models.Index(fields=['conversation', '-captured_at'], name='conversatio_convers_dcc920_idx'),
        ),
        migrations.AddConstraint(
            model_name='outcomesnapshot',
            constraint=models.UniqueConstraint(fields=('conversation', 'captured_at'), name='outcome_snapshots_conv_captured_unique'),
        ),
    ]
