# Generated by Django 5.1.15 on 2026-08-19 16:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('conversations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversationSemanticEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ordinal', models.PositiveIntegerField()),
                ('event_type', models.CharField(max_length=64)),
                ('actor', models.CharField(max_length=16)),
                ('turn_start', models.PositiveIntegerField()),
                ('turn_end', models.PositiveIntegerField()),
                ('occurred_at', models.DateTimeField(blank=True, null=True)),
                ('confidence', models.FloatField()),
                ('attributes', models.JSONField(blank=True, default=dict)),
                ('evidence_text', models.CharField(blank=True, default='', max_length=1000)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semantic_events', to='conversations.conversation')),
                ('entity_link', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='semantic_events', to='conversations.entitylink')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semantic_events', to='accounts.organization')),
            ],
            options={
                'ordering': ['extraction_run', 'conversation', 'ordinal'],
            },
        ),
        migrations.CreateModel(
            name='LearningCorpus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128)),
                ('version', models.CharField(max_length=64)),
                ('selection_criteria', models.JSONField(blank=True, default=dict)),
                ('member_count', models.PositiveIntegerField(default=0)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_corpora', to='accounts.organization')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LearningCorpusMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lb_lead_id', models.CharField(blank=True, default='', max_length=128)),
                ('lb_status_at_freeze', models.CharField(blank=True, default='', max_length=64)),
                ('turn_count_at_freeze', models.PositiveIntegerField(default=0)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corpus_memberships', to='conversations.conversation')),
                ('corpus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='conversations.learningcorpus')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='SemanticExtractionRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('extractor_version', models.CharField(max_length=64)),
                ('ontology_version', models.CharField(max_length=64)),
                ('prompt_version', models.CharField(max_length=64)),
                ('model', models.CharField(max_length=64)),
                ('provider', models.CharField(blank=True, default='', max_length=32)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('partial', 'Partial (some records failed)'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('records_processed', models.PositiveIntegerField(default=0)),
                ('records_failed', models.PositiveIntegerField(default=0)),
                ('events_created', models.PositiveIntegerField(default=0)),
                ('input_tokens', models.PositiveIntegerField(default=0)),
                ('output_tokens', models.PositiveIntegerField(default=0)),
                ('cost_usd', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('error_summary', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('corpus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extraction_runs', to='conversations.learningcorpus')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semantic_extraction_runs', to='accounts.organization')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SemanticEventEvaluation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewer', models.CharField(blank=True, default='', max_length=128)),
                ('judgment', models.CharField(choices=[('correct', 'Correct'), ('partially_correct', 'Partially correct'), ('incorrect', 'Incorrect'), ('missed_event', 'Missed event (should exist)'), ('wrong_event_type', 'Wrong event type'), ('wrong_actor', 'Wrong actor'), ('wrong_span', 'Wrong turn span')], max_length=32)),
                ('expected_event_type', models.CharField(blank=True, default='', max_length=64)),
                ('expected_turn_start', models.PositiveIntegerField(blank=True, null=True)),
                ('expected_turn_end', models.PositiveIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semantic_evaluations', to='conversations.conversation')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='conversations.conversationsemanticevent')),
                ('extraction_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='conversations.semanticextractionrun')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='conversationsemanticevent',
            name='extraction_run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='conversations.semanticextractionrun'),
        ),
        migrations.AddIndex(
            model_name='learningcorpus',
            index=models.Index(fields=['org', 'name'], name='conversatio_org_id_edc058_idx'),
        ),
        migrations.AddConstraint(
            model_name='learningcorpus',
            constraint=models.UniqueConstraint(fields=('org', 'name', 'version'), name='learning_corpus_org_name_version_unique'),
        ),
        migrations.AddIndex(
            model_name='learningcorpusmember',
            index=models.Index(fields=['corpus', 'lb_status_at_freeze'], name='conversatio_corpus__e8927f_idx'),
        ),
        migrations.AddIndex(
            model_name='learningcorpusmember',
            index=models.Index(fields=['conversation'], name='conversatio_convers_5cf191_idx'),
        ),
        migrations.AddConstraint(
            model_name='learningcorpusmember',
            constraint=models.UniqueConstraint(fields=('corpus', 'conversation'), name='corpus_member_conv_unique'),
        ),
        migrations.AddIndex(
            model_name='semanticextractionrun',
            index=models.Index(fields=['corpus', 'status'], name='conversatio_corpus__edecee_idx'),
        ),
        migrations.AddIndex(
            model_name='semanticextractionrun',
            index=models.Index(fields=['-started_at'], name='conversatio_started_66ddec_idx'),
        ),
        migrations.AddConstraint(
            model_name='semanticextractionrun',
            constraint=models.UniqueConstraint(fields=('corpus', 'extractor_version', 'ontology_version', 'prompt_version', 'model'), name='extraction_run_version_key_unique'),
        ),
        migrations.AddIndex(
            model_name='semanticeventevaluation',
            index=models.Index(fields=['extraction_run', 'judgment'], name='conversatio_extract_ab8b9b_idx'),
        ),
        migrations.AddIndex(
            model_name='semanticeventevaluation',
            index=models.Index(fields=['conversation'], name='conversatio_convers_a6f4dc_idx'),
        ),
        migrations.AddIndex(
            model_name='conversationsemanticevent',
            index=models.Index(fields=['extraction_run', 'event_type'], name='conversatio_extract_f40334_idx'),
        ),
        migrations.AddIndex(
            model_name='conversationsemanticevent',
            index=models.Index(fields=['conversation', 'extraction_run'], name='conversatio_convers_016d55_idx'),
        ),
        migrations.AddIndex(
            model_name='conversationsemanticevent',
            index=models.Index(fields=['event_type'], name='conversatio_event_t_4050de_idx'),
        ),
        migrations.AddIndex(
            model_name='conversationsemanticevent',
            index=models.Index(fields=['actor'], name='conversatio_actor_fec6fd_idx'),
        ),
        migrations.AddConstraint(
            model_name='conversationsemanticevent',
            constraint=models.UniqueConstraint(fields=('extraction_run', 'conversation', 'ordinal'), name='semantic_event_run_conv_ordinal_unique'),
        ),
    ]
