# Generated by Django 5.1.15 on 2026-08-19 19:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('conversations', '0002_conversationsemanticevent_learningcorpus_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatternDiscoveryRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('analyzer_version', models.CharField(max_length=64)),
                ('split_seed', models.PositiveIntegerField(help_text='Random seed for the stratified 80/20 split. Same seed = same split.')),
                ('config', models.JSONField(blank=True, default=dict, help_text='Discovery config snapshot')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('discovery_conversation_ids', models.JSONField(blank=True, default=list)),
                ('holdout_conversation_ids', models.JSONField(blank=True, default=list)),
                ('positive_class_statuses', models.JSONField(blank=True, default=list)),
                ('negative_class_statuses', models.JSONField(blank=True, default=list)),
                ('n_discovery_positive', models.PositiveIntegerField(default=0)),
                ('n_discovery_negative', models.PositiveIntegerField(default=0)),
                ('n_holdout_positive', models.PositiveIntegerField(default=0)),
                ('n_holdout_negative', models.PositiveIntegerField(default=0)),
                ('candidates_found', models.PositiveIntegerField(default=0)),
                ('candidates_reproduced_on_holdout', models.PositiveIntegerField(default=0)),
                ('error_summary', models.TextField(blank=True, default='')),
                ('corpus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pattern_discovery_runs', to='conversations.learningcorpus')),
                ('extraction_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pattern_discovery_runs', to='conversations.semanticextractionrun')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pattern_discovery_runs', to='accounts.organization')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CandidatePattern',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pattern_id', models.CharField(help_text='Like P0017 within the discovery_run', max_length=32)),
                ('kind', models.CharField(choices=[('single_event', 'Single event presence'), ('ordered_sequence', 'Ordered N-gram sequence')], max_length=32)),
                ('sequence', models.JSONField()),
                ('temporal_class', models.CharField(choices=[('PRE_OUTCOME', 'Pre-outcome (predictive candidate)'), ('OUTCOME_PROXY', 'Near-tautological with label'), ('POST_OUTCOME', 'After outcome determined'), ('UNKNOWN', 'Ambiguous / mixed timing'), ('MIXED', 'Sequence spans multiple classes')], max_length=16)),
                ('discovery_positive_present', models.PositiveIntegerField(default=0)),
                ('discovery_positive_total', models.PositiveIntegerField(default=0)),
                ('discovery_negative_present', models.PositiveIntegerField(default=0)),
                ('discovery_negative_total', models.PositiveIntegerField(default=0)),
                ('discovery_positive_rate', models.FloatField(default=0.0)),
                ('discovery_negative_rate', models.FloatField(default=0.0)),
                ('discovery_effect_size', models.FloatField(default=0.0, help_text='pos_rate - neg_rate')),
                ('discovery_effect_ci_low', models.FloatField(default=0.0)),
                ('discovery_effect_ci_high', models.FloatField(default=0.0)),
                ('length_adjusted_direction_short', models.CharField(blank=True, default='', max_length=16)),
                ('length_adjusted_direction_long', models.CharField(blank=True, default='', max_length=16)),
                ('holdout_positive_present', models.PositiveIntegerField(default=0)),
                ('holdout_positive_total', models.PositiveIntegerField(default=0)),
                ('holdout_negative_present', models.PositiveIntegerField(default=0)),
                ('holdout_negative_total', models.PositiveIntegerField(default=0)),
                ('holdout_positive_rate', models.FloatField(default=0.0)),
                ('holdout_negative_rate', models.FloatField(default=0.0)),
                ('holdout_effect_size', models.FloatField(default=0.0)),
                ('holdout_status', models.CharField(blank=True, choices=[('reproduced', 'Direction reproduced'), ('not_reproduced', 'Direction did NOT reproduce'), ('underpowered', 'Holdout n too small')], default='', max_length=32)),
                ('evidence_positive_ids', models.JSONField(blank=True, default=list)),
                ('evidence_negative_ids', models.JSONField(blank=True, default=list)),
                ('discovery_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='conversations.patterndiscoveryrun')),
            ],
            options={
                'ordering': ['discovery_run', 'pattern_id'],
            },
        ),
        migrations.AddIndex(
            model_name='patterndiscoveryrun',
            index=models.Index(fields=['corpus', 'status'], name='conversatio_corpus__f9c583_idx'),
        ),
        migrations.AddConstraint(
            model_name='patterndiscoveryrun',
            constraint=models.UniqueConstraint(fields=('corpus', 'extraction_run', 'analyzer_version', 'split_seed'), name='pattern_run_key_unique'),
        ),
        migrations.AddIndex(
            model_name='candidatepattern',
            index=models.Index(fields=['discovery_run', 'temporal_class'], name='conversatio_discove_1cc33e_idx'),
        ),
        migrations.AddIndex(
            model_name='candidatepattern',
            index=models.Index(fields=['discovery_run', '-discovery_effect_size'], name='conversatio_discove_60dd66_idx'),
        ),
        migrations.AddConstraint(
            model_name='candidatepattern',
            constraint=models.UniqueConstraint(fields=('discovery_run', 'pattern_id'), name='candidate_pattern_id_unique'),
        ),
    ]
