# Generated by Django 6.0.7 on 2026-08-19 22:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('conversations', '0003_patterndiscoveryrun_candidatepattern_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConditionalAnalysisRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('analyzer_version', models.CharField(max_length=64)),
                ('split_seed', models.PositiveIntegerField(help_text='Same-seed convention as PatternDiscoveryRun for split reproducibility.')),
                ('config', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('discovery_conversation_ids', models.JSONField(blank=True, default=list)),
                ('holdout_conversation_ids', models.JSONField(blank=True, default=list)),
                ('positive_class_statuses', models.JSONField(blank=True, default=list)),
                ('negative_class_statuses', models.JSONField(blank=True, default=list)),
                ('n_discovery_positive', models.PositiveIntegerField(default=0)),
                ('n_discovery_negative', models.PositiveIntegerField(default=0)),
                ('n_holdout_positive', models.PositiveIntegerField(default=0)),
                ('n_holdout_negative', models.PositiveIntegerField(default=0)),
                ('n_excluded_lead_mismatch', models.PositiveIntegerField(default=0)),
                ('n_excluded_status', models.PositiveIntegerField(default=0)),
                ('n_discovery_observations', models.PositiveIntegerField(default=0)),
                ('n_holdout_observations', models.PositiveIntegerField(default=0)),
                ('patterns_found', models.PositiveIntegerField(default=0)),
                ('patterns_supported', models.PositiveIntegerField(default=0)),
                ('patterns_reproduced_on_holdout', models.PositiveIntegerField(default=0)),
                ('error_summary', models.TextField(blank=True, default='')),
                ('corpus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditional_analysis_runs', to='conversations.learningcorpus')),
                ('extraction_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditional_analysis_runs', to='conversations.semanticextractionrun')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditional_analysis_runs', to='accounts.organization')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConditionalActionPattern',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pattern_id', models.CharField(help_text='Like CA0017 within the analysis_run', max_length=32)),
                ('condition_event', models.CharField(help_text='CUSTOMER_SIGNAL ontology event type', max_length=64)),
                ('action_event', models.CharField(help_text='AGENT_ACTION ontology event type', max_length=64)),
                ('d_ca_positive', models.PositiveIntegerField(default=0)),
                ('d_ca_negative', models.PositiveIntegerField(default=0)),
                ('d_co_positive', models.PositiveIntegerField(default=0)),
                ('d_co_negative', models.PositiveIntegerField(default=0)),
                ('d_cn_positive', models.PositiveIntegerField(default=0)),
                ('d_cn_negative', models.PositiveIntegerField(default=0)),
                ('d_ca_rate', models.FloatField(default=0.0)),
                ('d_co_rate', models.FloatField(default=0.0)),
                ('d_cn_rate', models.FloatField(default=0.0)),
                ('d_primary_effect', models.FloatField(default=0.0, help_text='rate(CA) - rate(CO) — the business question')),
                ('d_primary_ci_low', models.FloatField(default=0.0)),
                ('d_primary_ci_high', models.FloatField(default=0.0)),
                ('d_secondary_effect', models.FloatField(default=0.0, help_text='rate(CA) - rate(CN) — reported, not ranked on')),
                ('d_secondary_ci_low', models.FloatField(default=0.0)),
                ('d_secondary_ci_high', models.FloatField(default=0.0)),
                ('length_adjusted_direction_short', models.CharField(blank=True, default='', max_length=16)),
                ('length_adjusted_direction_long', models.CharField(blank=True, default='', max_length=16)),
                ('h_ca_positive', models.PositiveIntegerField(default=0)),
                ('h_ca_negative', models.PositiveIntegerField(default=0)),
                ('h_co_positive', models.PositiveIntegerField(default=0)),
                ('h_co_negative', models.PositiveIntegerField(default=0)),
                ('h_cn_positive', models.PositiveIntegerField(default=0)),
                ('h_cn_negative', models.PositiveIntegerField(default=0)),
                ('h_primary_effect', models.FloatField(default=0.0)),
                ('h_secondary_effect', models.FloatField(default=0.0)),
                ('overall_status', models.CharField(choices=[('SUPPORTED', 'Enough support in both cells for a comparison'), ('DIRECTIONAL_ONLY', 'C+A cell supported but comparator too small'), ('UNDERPOWERED', 'C+A cell below min_cell_support')], default='UNDERPOWERED', max_length=32)),
                ('holdout_status', models.CharField(choices=[('HOLDOUT_REPRODUCED', 'Primary direction reproduced on holdout'), ('HOLDOUT_FAILED', 'Primary direction did NOT reproduce'), ('UNDERPOWERED', 'Holdout cell too small')], default='UNDERPOWERED', max_length=32)),
                ('evidence_positive_ids', models.JSONField(blank=True, default=list)),
                ('evidence_negative_ids', models.JSONField(blank=True, default=list)),
                ('analysis_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patterns', to='conversations.conditionalanalysisrun')),
            ],
            options={
                'ordering': ['analysis_run', 'pattern_id'],
            },
        ),
        migrations.AddIndex(
            model_name='conditionalanalysisrun',
            index=models.Index(fields=['corpus', 'status'], name='conversatio_corpus__839597_idx'),
        ),
        migrations.AddConstraint(
            model_name='conditionalanalysisrun',
            constraint=models.UniqueConstraint(fields=('corpus', 'extraction_run', 'analyzer_version', 'split_seed'), name='conditional_run_key_unique'),
        ),
        migrations.AddIndex(
            model_name='conditionalactionpattern',
            index=models.Index(fields=['analysis_run', 'condition_event'], name='conversatio_analysi_a06f86_idx'),
        ),
        migrations.AddIndex(
            model_name='conditionalactionpattern',
            index=models.Index(fields=['analysis_run', 'overall_status'], name='conversatio_analysi_ab75fc_idx'),
        ),
        migrations.AddIndex(
            model_name='conditionalactionpattern',
            index=models.Index(fields=['analysis_run', '-d_primary_effect'], name='conversatio_analysi_0f28b7_idx'),
        ),
        migrations.AddConstraint(
            model_name='conditionalactionpattern',
            constraint=models.UniqueConstraint(fields=('analysis_run', 'pattern_id'), name='conditional_pattern_id_unique'),
        ),
        migrations.AddConstraint(
            model_name='conditionalactionpattern',
            constraint=models.UniqueConstraint(fields=('analysis_run', 'condition_event', 'action_event'), name='conditional_pattern_ca_unique'),
        ),
    ]
