# Generated by Django 6.0.7 on 2026-08-20 02:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('conversations', '0004_conditional_analysis_run_and_pattern'),
    ]

    operations = [
        migrations.CreateModel(
            name='BehavioralPolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('condition_event', models.CharField(max_length=64)),
                ('prescribed_action_events', models.JSONField(default=list)),
                ('channel', models.CharField(choices=[('text', 'Text (LB SMS/chat replies)'), ('voice', 'Voice (Callio)'), ('policy', 'Channel-agnostic policy')], default='text', max_length=16)),
                ('source_rule_text', models.TextField()),
                ('source_pointer', models.JSONField(blank=True, default=dict)),
                ('extraction_confidence', models.FloatField(default=1.0)),
                ('ordinal', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['snapshot', 'ordinal'],
            },
        ),
        migrations.CreateModel(
            name='TenantConfigSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_system', models.CharField(choices=[('leadbridge', 'LeadBridge'), ('callio', 'Callio')], max_length=32)),
                ('tenant_external_id', models.CharField(max_length=128)),
                ('service_group', models.CharField(blank=True, default='', max_length=64)),
                ('contract_version', models.CharField(max_length=32)),
                ('raw_config', models.JSONField()),
                ('raw_config_sha256', models.CharField(max_length=64)),
                ('fetched_from_url', models.CharField(blank=True, default='', max_length=512)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_config_snapshots', to='accounts.organization')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PolicyAlignmentAssessment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('alignment_status', models.CharField(choices=[('CONFIG_SUPPORTED', 'Prescribed behavior supported by evidence'), ('CONFIG_QUESTIONABLE', 'Prescribed weaker than alternatives'), ('EXECUTION_GAP', 'Config prescribes X, observations do Y'), ('INSUFFICIENT_EVIDENCE', 'Cells too small to compare')], max_length=32)),
                ('deterministic_rationale', models.TextField()),
                ('llm_narrative', models.TextField(blank=True, default='')),
                ('evidence_conversation_ids', models.JSONField(blank=True, default=list)),
                ('analysis_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alignment_assessments', to='conversations.conditionalanalysisrun')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='conversations.behavioralpolicy')),
                ('primary_pattern', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='conversations.conditionalactionpattern')),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alignment_assessments', to='conversations.tenantconfigsnapshot')),
            ],
            options={
                'ordering': ['snapshot', 'policy'],
            },
        ),
        migrations.AddField(
            model_name='behavioralpolicy',
            name='snapshot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policies', to='conversations.tenantconfigsnapshot'),
        ),
        migrations.AddIndex(
            model_name='tenantconfigsnapshot',
            index=models.Index(fields=['org', 'source_system', 'tenant_external_id', '-created_at'], name='conversatio_org_id_227482_idx'),
        ),
        migrations.AddConstraint(
            model_name='tenantconfigsnapshot',
            constraint=models.UniqueConstraint(fields=('org', 'source_system', 'tenant_external_id', 'service_group', 'raw_config_sha256'), name='tenant_config_snapshot_dedup_unique'),
        ),
        migrations.AddIndex(
            model_name='policyalignmentassessment',
            index=models.Index(fields=['snapshot', 'alignment_status'], name='conversatio_snapsho_2b2398_idx'),
        ),
        migrations.AddIndex(
            model_name='policyalignmentassessment',
            index=models.Index(fields=['analysis_run', 'alignment_status'], name='conversatio_analysi_267fc7_idx'),
        ),
        migrations.AddConstraint(
            model_name='policyalignmentassessment',
            constraint=models.UniqueConstraint(fields=('snapshot', 'analysis_run', 'policy'), name='alignment_assessment_unique'),
        ),
        migrations.AddIndex(
            model_name='behavioralpolicy',
            index=models.Index(fields=['snapshot', 'condition_event'], name='conversatio_snapsho_be902b_idx'),
        ),
        migrations.AddIndex(
            model_name='behavioralpolicy',
            index=models.Index(fields=['snapshot', 'channel'], name='conversatio_snapsho_30af22_idx'),
        ),
    ]
