# Generated by Django 6.0.7 on 2026-08-20 13:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('conversations', '0005_tenant_config_snapshot_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerStateInferenceRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('inference_version', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('n_conversations_inferred', models.PositiveIntegerField(default=0)),
                ('n_transitions_emitted', models.PositiveIntegerField(default=0)),
                ('config_snapshot_hash', models.CharField(blank=True, default='', help_text='Rules-config hash for audit trail', max_length=64)),
                ('corpus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='state_inference_runs', to='conversations.learningcorpus')),
                ('extraction_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='state_inference_runs', to='conversations.semanticextractionrun')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='state_inference_runs', to='accounts.organization')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InferredCustomerState',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ordinal', models.PositiveIntegerField(help_text='0-based position in this conversation state history')),
                ('state', models.CharField(max_length=32)),
                ('previous_state', models.CharField(max_length=32)),
                ('trigger_event_types', models.JSONField(default=list, help_text='Ontology event types that produced this transition')),
                ('trigger_event_ordinals', models.JSONField(default=list, help_text='Semantic-event ordinals (provenance to ConversationSemanticEvent.ordinal)')),
                ('effective_turn', models.PositiveIntegerField(help_text='DB parent turn_start of the latest triggering event')),
                ('reason', models.TextField(blank=True, default='')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inferred_states', to='conversations.conversation')),
                ('inference_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='states', to='conversations.customerstateinferencerun')),
            ],
            options={
                'ordering': ['inference_run', 'conversation', 'ordinal'],
            },
        ),
        migrations.AddIndex(
            model_name='customerstateinferencerun',
            index=models.Index(fields=['corpus', 'status'], name='conversatio_corpus__dc5639_idx'),
        ),
        migrations.AddConstraint(
            model_name='customerstateinferencerun',
            constraint=models.UniqueConstraint(fields=('corpus', 'extraction_run', 'inference_version'), name='state_inference_run_unique'),
        ),
        migrations.AddIndex(
            model_name='inferredcustomerstate',
            index=models.Index(fields=['inference_run', 'state'], name='conversatio_inferen_10e5d4_idx'),
        ),
        migrations.AddIndex(
            model_name='inferredcustomerstate',
            index=models.Index(fields=['conversation', 'inference_run'], name='conversatio_convers_3b2290_idx'),
        ),
        migrations.AddConstraint(
            model_name='inferredcustomerstate',
            constraint=models.UniqueConstraint(fields=('inference_run', 'conversation', 'ordinal'), name='inferred_state_run_conv_ordinal_unique'),
        ),
    ]
