# Generated by Django 6.0.7 on 2026-08-20 14:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('conversations', '0006_inferred_customer_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendationRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('synthesizer_version', models.CharField(max_length=64)),
                ('llm_model', models.CharField(blank=True, default='', max_length=64)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('recommendations_generated', models.PositiveIntegerField(default=0)),
                ('llm_input_tokens', models.PositiveIntegerField(default=0)),
                ('llm_output_tokens', models.PositiveIntegerField(default=0)),
                ('llm_cost_usd', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('error_summary', models.TextField(blank=True, default='')),
                ('conditional_analysis_run', models.ForeignKey(blank=True, help_text='Optional — used for outcome-statistic provenance if present', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommendation_runs', to='conversations.conditionalanalysisrun')),
                ('config_snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_runs', to='conversations.tenantconfigsnapshot')),
                ('corpus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_runs', to='conversations.learningcorpus')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_runs', to='accounts.organization')),
                ('state_inference_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_runs', to='conversations.customerstateinferencerun')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BehaviorRecommendation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recommendation_id', models.CharField(help_text='Human-readable id like R0001 within the run', max_length=32)),
                ('rec_class', models.CharField(choices=[('STATE_COVERAGE_GAP', 'Validated state has uncovered contributing signals'), ('STATE_PARTIAL_COVERAGE', 'State recognized but some paths uncovered'), ('CONFIG_ALIGNMENT', 'Configuration addresses validated state/signal'), ('OBSERVED_STATE_INSIGHT', 'Useful state/transition insight; no config change justified'), ('INSUFFICIENT_EVIDENCE', 'Interesting issue but MUST NOT become an action recommendation')], max_length=32)),
                ('confidence', models.CharField(choices=[('HIGH', 'High — reproduced on holdout, material lift, low ambiguity'), ('MEDIUM', 'Medium — reproduced but small n or noisy'), ('LOW', 'Low — directional only'), ('INSUFFICIENT', 'Not enough evidence for confidence')], max_length=16)),
                ('subject_state', models.CharField(blank=True, default='', help_text='CustomerState this rec is about, if any', max_length=32)),
                ('subject_signals', models.JSONField(blank=True, default=list, help_text='Ontology signal event_types this rec references')),
                ('linked_policy_ids', models.JSONField(blank=True, default=list, help_text='BehavioralPolicy IDs (from config snapshot) related to this rec')),
                ('linked_transition', models.JSONField(blank=True, default=dict, help_text='{"previous_state": ..., "state": ...} when this rec is about a state transition')),
                ('evidence', models.JSONField(blank=True, default=dict, help_text='Structured evidence chain. Example keys: state_lift, state_holdout_status, state_n, covered_signals, uncovered_signals, corpus_baseline_positive_rate.')),
                ('supporting_conversation_ids', models.JSONField(blank=True, default=list, help_text='Up to 20 evidence conversation IDs')),
                ('observation', models.TextField(blank=True, default='', help_text='One-sentence factual observation, LLM-drafted')),
                ('interpretation', models.TextField(blank=True, default='', help_text='One-sentence interpretation of what the observation means, LLM-drafted')),
                ('proposed_action_scope', models.CharField(choices=[('config_addition', 'Add new policy/rule to LB config'), ('config_review', 'Human review of existing policy'), ('monitoring_only', 'Watch this state — no config change yet'), ('no_action_recommended', 'Explicitly no action')], default='no_action_recommended', max_length=32)),
                ('proposed_action', models.TextField(blank=True, default='', help_text='Optional proposed action, LLM-drafted; blank when proposed_action_scope=NO_ACTION_RECOMMENDED')),
                ('limitations', models.TextField(blank=True, default='', help_text='REQUIRED: what we do not know; caveats on the claim')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='conversations.recommendationrun')),
            ],
            options={
                'ordering': ['run', 'recommendation_id'],
            },
        ),
        migrations.AddIndex(
            model_name='recommendationrun',
            index=models.Index(fields=['corpus', 'status'], name='conversatio_corpus__de1855_idx'),
        ),
        migrations.AddConstraint(
            model_name='recommendationrun',
            constraint=models.UniqueConstraint(fields=('corpus', 'state_inference_run', 'config_snapshot', 'synthesizer_version'), name='recommendation_run_unique'),
        ),
        migrations.AddIndex(
            model_name='behaviorrecommendation',
            index=models.Index(fields=['run', 'rec_class'], name='conversatio_run_id_96badc_idx'),
        ),
        migrations.AddIndex(
            model_name='behaviorrecommendation',
            index=models.Index(fields=['run', 'confidence'], name='conversatio_run_id_a64b78_idx'),
        ),
        migrations.AddConstraint(
            model_name='behaviorrecommendation',
            constraint=models.UniqueConstraint(fields=('run', 'recommendation_id'), name='recommendation_id_unique'),
        ),
    ]
