# Generated by Django 6.0.7 on 2026-08-20 14:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0007_behavior_recommendation'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendationLifecycleState',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('state', models.CharField(choices=[('new', 'New — never viewed'), ('viewed', 'Viewed — surfaced to user'), ('accepted', 'Accepted — user endorses (does NOT apply changes in v1)'), ('dismissed', 'Dismissed — user rejected')], default='new', max_length=16)),
                ('dismissal_reason', models.CharField(blank=True, default='', help_text='Optional short tag like "not_applicable", "already_doing_this", "insufficient_evidence"', max_length=64)),
                ('dismissal_note', models.TextField(blank=True, default='', help_text='Optional free-text explanation')),
                ('state_changed_at', models.DateTimeField(auto_now=True)),
                ('state_changed_by', models.CharField(blank=True, default='', max_length=255)),
                ('history', models.JSONField(blank=True, default=list)),
                ('recommendation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lifecycle', to='conversations.behaviorrecommendation')),
            ],
            options={
                'ordering': ['-state_changed_at'],
                'indexes': [models.Index(fields=['recommendation', 'state'], name='conversatio_recomme_50303d_idx')],
            },
        ),
    ]
