# Generated by Django 6.0.7 on 2026-08-20 17:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0008_recommendation_lifecycle_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendationProposal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('target_system', models.CharField(choices=[('leadbridge', 'LeadBridge')], default='leadbridge', max_length=32)),
                ('change_type', models.CharField(choices=[('add_behavior_rule', 'Add a behavior rule for a customer signal')], max_length=32)),
                ('condition', models.CharField(max_length=64)),
                ('scope', models.CharField(blank=True, default='', max_length=64)),
                ('proposed_behavior_summary', models.TextField()),
                ('proposed_behavior_detail', models.TextField()),
                ('config_snapshot_hash', models.CharField(help_text='Copy of snapshot.raw_config_sha256 — consumer compares to its own current-config hash at apply time', max_length=64)),
                ('status', models.CharField(choices=[('proposed', 'Proposed — ready for consumer preview/apply'), ('applied', 'Applied — consumer reported successful write'), ('stale', 'Stale — consumer reported config drift; regenerate'), ('failed', 'Failed — consumer reported an apply error')], default='proposed', max_length=16)),
                ('consumer_applied_at', models.DateTimeField(blank=True, null=True)),
                ('consumer_error', models.TextField(blank=True, default='')),
                ('generator_version', models.CharField(max_length=64)),
                ('llm_model', models.CharField(blank=True, default='', max_length=64)),
                ('llm_input_tokens', models.PositiveIntegerField(default=0)),
                ('llm_output_tokens', models.PositiveIntegerField(default=0)),
                ('llm_cost_usd', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('config_snapshot', models.ForeignKey(help_text='Snapshot BehaviorOS analyzed when generating the proposal', on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='conversations.tenantconfigsnapshot')),
                ('recommendation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='proposal', to='conversations.behaviorrecommendation')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='conversatio_status_7549ef_idx'), models.Index(fields=['config_snapshot', 'status'], name='conversatio_config__4e6ea7_idx')],
            },
        ),
    ]
